name: CI/CD Pipeline (Self-Hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run placeholder tests
      run: |
        echo "Running placeholder tests..."
        echo "No tests defined. Skipping."

    - name: Build Docker image
      run: |
        docker build -t test-app:latest .

    - name: Deploy locally
      run: |
        docker stop app || true
        docker rm app || true
        docker run -d --name app -p 80:80 test-app:latest